# UI layout
screen.columns=2
screen=SHADOW_DARKNESS TOON_STEPS VIBRANCE DAY_TINT NIGHT_TINT GLOWING_ORE_MULT OUTLINE_WIDTH OUTLINE_BRIGHTNESS BORDER_EXPERIMENTAL shadowDistance shadowMapResolution WORLD_RENDER_DISTANCE

# Sliders
sliders=SHADOW_DARKNESS TOON_STEPS VIBRANCE DAY_TINT NIGHT_TINT GLOWING_ORE_MULT OUTLINE_WIDTH OUTLINE_BRIGHTNESS shadowDistance WORLD_RENDER_DISTANCE
